mysocial/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(("publications.urls", "publications"), namespace="publications")),


]


if settings.DEBUG :
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

publications/urls.py
from django.urls import path
from .views import  Feed, create_post
urlpatterns = [
    path("", Feed.as_view(), name = "feed"),
    path("create_post", create_post, name="create_post")
]

base/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class ModelBase(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    state = models.BooleanField(default=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    updated_by = models.IntegerField(null=True, blank=True)

    class Meta:
        abstract = True

publications/models.py
from django.db import models
from base.models import  ModelBase
# Create your models here.

class Publication(ModelBase):
    description = models.CharField(max_length=250)
    media = models.FileField(null = True, blank=True, upload_to="post/")
    likes = models.IntegerField(default=0)
    dislikes = models.IntegerField(default=0)
    # views = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.created_by.username} - {self.created_at}"


class Comment(ModelBase):
    content = models.CharField(max_length=200)
    publication = models.ForeignKey(Publication, on_delete=models.CASCADE, related_name="comments")

    def __str__(self):
        return f"{self.created_by} - {self.created_at}"

base/views.py
from django.shortcuts import render

# Create your views here.

publications/views.py
from django.shortcuts import render, HttpResponse
from django.views.generic import ListView, TemplateView

from publications.models import Publication


# Create your views here.
class Feed(ListView):
    template_name = "publications/feed.html"
    model = Publication


def create_post(request):
    if request.method == "POST":

        print(type(request.FILES["image"]))
        print(type(request.POST["contenido"]))
        Publication(description=request.POST["contenido"], media=request.FILES["image"], created_by=request.user).save()

publications/templates/components/new-input.html
{% load static %}
<div class="newpst-input">
    <form method="post" action="{% url 'publications:create_post' %}" enctype="multipart/form-data">
        {% csrf_token %}
        <textarea rows="2" placeholder="contenido ;)" id = "contenido" name = "contenido"></textarea>
        <div class="attachments">
            <ul>
                <li>
                    <i class="fa fa-music"></i>
                    <label class="fileContainer">
                        <input  type="file">
                    </label>
                </li>
                <li>
                    <i class="fa fa-image"></i>
                    <label class="fileContainer">
                        <input type="file" id = "image" name = "image">
                    </label>
                </li>
                <li>
                    <i class="fa fa-video-camera"></i>
                    <label class="fileContainer">
                        <input type="file">
                    </label>
                </li>
                <li>
                    <i class="fa fa-camera"></i>
                    <label class="fileContainer">
                        <input type="file" >
                    </label>
                </li>
                <li>
                    <button type="submit">Post</button>
                </li>
            </ul>
        </div>
    </form>
</div>

publications/templates/components/user-post.html
{%  load static %}
<div class="central-meta item">
    {% for post in publication_list %}
									<div class="user-post">
										<div class="friend-info">
											<figure>
												<img src="{% static 'images/resources/friend-avatar10.jpg' %}" alt="user">
											</figure>
											<div class="friend-name">
												<ins><a href="time-line.html" title="">{{ post.created_by.username }}</a></ins>
												<span>published: {{ post.created_at }}</span>
											</div>
											<div class="post-meta">
												<img src="{{post.media.url}}" alt="media">
												<div class="we-video-info">
													<ul>
														<li>
															<span class="views" data-toggle="tooltip" title="views">
																<i class="fa fa-eye"></i>
																<ins>1.2k</ins>
															</span>
														</li>
														<li>
															<span class="comment" data-toggle="tooltip" title="Comments">
																<i class="fa fa-comments-o"></i>
																<ins>52</ins>
															</span>
														</li>
														<li>
															<span class="like" data-toggle="tooltip" title="like">
																<i class="ti-heart"></i>
																<ins>{{ post.likes }}</ins>
															</span>
														</li>
														<li>
															<span class="dislike" data-toggle="tooltip" title="dislike">
																<i class="ti-heart-broken"></i>
																<ins>{{ post.dislikes }}</ins>
															</span>
														</li>
														<li class="social-media">
															<div class="menu">
															  <div class="btn trigger"><i class="fa fa-share-alt"></i></div>
															  <div class="rotater">
																<div class="btn btn-icon"><a href="#" title=""><i class="fa fa-html5"></i></a></div>
															  </div>
															  <div class="rotater">
																<div class="btn btn-icon"><a href="#" title=""><i class="fa fa-facebook"></i></a></div>
															  </div>
															  <div class="rotater">
																<div class="btn btn-icon"><a href="#" title=""><i class="fa fa-google-plus"></i></a></div>
															  </div>
															  <div class="rotater">
																<div class="btn btn-icon"><a href="#" title=""><i class="fa fa-twitter"></i></a></div>
															  </div>
															  <div class="rotater">
																<div class="btn btn-icon"><a href="#" title=""><i class="fa fa-css3"></i></a></div>
															  </div>
															  <div class="rotater">
																<div class="btn btn-icon"><a href="#" title=""><i class="fa fa-instagram"></i></a>
																</div>
															  </div>
																<div class="rotater">
																<div class="btn btn-icon"><a href="#" title=""><i class="fa fa-dribbble"></i></a>
																</div>
															  </div>
															  <div class="rotater">
																<div class="btn btn-icon"><a href="#" title=""><i class="fa fa-pinterest"></i></a>
																</div>
															  </div>

															</div>
														</li>
													</ul>
												</div>
												<div class="description">

													<p>
{#                                                        World's most beautiful car in Curabitur <a href="#" title="">#test drive booking !</a> the most beatuiful car available in america and the saudia arabia, you can book your test drive by our official website#}
														{{ post.description }}
													</p>
												</div>
											</div>
										</div>
										<div class="coment-area">
											<ul class="we-comet">
												<li>
													<div class="comet-avatar">
														<img src="{% static 'images/resources/comet-1.jpg' %}" alt="">
													</div>
													<div class="we-comment">
														<div class="coment-head">
															<h5><a href="time-line.html" title="">Jason borne</a></h5>
															<span>1 year ago</span>
															<a class="we-reply" href="#" title="Reply"><i class="fa fa-reply"></i></a>
														</div>
														<p>we are working for the dance and sing songs. this car is very awesome for the youngster. please vote this car and like our post</p>
													</div>
													<ul>
														<li>
															<div class="comet-avatar">
																<img src="{% static 'images/resources/comet-2.jpg' %}" alt="">
															</div>
															<div class="we-comment">
																<div class="coment-head">
																	<h5><a href="time-line.html" title="">alexendra dadrio</a></h5>
																	<span>1 month ago</span>
																	<a class="we-reply" href="#" title="Reply"><i class="fa fa-reply"></i></a>
																</div>
																<p>yes, really very awesome car i see the features of this car in the official website of <a href="#" title="">#Mercedes-Benz</a> and really impressed :-)</p>
															</div>
														</li>
														<li>
															<div class="comet-avatar">
																<img src="{% static 'images/resources/comet-3.jpg' %}" alt="">
															</div>
															<div class="we-comment">
																<div class="coment-head">
																	<h5><a href="time-line.html" title="">Olivia</a></h5>
																	<span>16 days ago</span>
																	<a class="we-reply" href="#" title="Reply"><i class="fa fa-reply"></i></a>
																</div>
																<p>i like lexus cars, lexus cars are most beautiful with the awesome features, but this car is really outstanding than lexus</p>
															</div>
														</li>
													</ul>
												</li>
												<li>
													<div class="comet-avatar">
														<img src="{% static 'images/resources/comet-1.jpg' %}" alt="">
													</div>
													<div class="we-comment">
														<div class="coment-head">
															<h5><a href="time-line.html" title="">Donald Trump</a></h5>
															<span>1 week ago</span>
															<a class="we-reply" href="#" title="Reply"><i class="fa fa-reply"></i></a>
														</div>
														<p>we are working for the dance and sing songs. this video is very awesome for the youngster. please vote this video and like our channel
															<i class="em em-smiley"></i>
														</p>
													</div>
												</li>
												<li>
													<a href="#" title="" class="showmore underline">more comments</a>
												</li>
												<li class="post-comment">
													<div class="comet-avatar">
														<img src="{% static 'images/resources/comet-1.jpg' %}" alt="">
													</div>
													<div class="post-comt-box">
														<form method="post">
															<textarea placeholder="Post your comment"></textarea>
															<div class="add-smiles">
																<span class="em em-expressionless" title="add icon"></span>
															</div>
															<div class="smiles-bunch">
																<i class="em em---1"></i>
																<i class="em em-smiley"></i>
																<i class="em em-anguished"></i>
																<i class="em em-laughing"></i>
																<i class="em em-angry"></i>
																<i class="em em-astonished"></i>
																<i class="em em-blush"></i>
																<i class="em em-disappointed"></i>
																<i class="em em-worried"></i>
																<i class="em em-kissing_heart"></i>
																<i class="em em-rage"></i>
																<i class="em em-stuck_out_tongue"></i>
															</div>
															<button type="submit"></button>
														</form>
													</div>
												</li>
											</ul>
										</div>
									</div>
    {% endfor %}
								</div>

publications/templates/publications/feed.html
{% extends 'base/base.html' %}

templates/base/aside.html
{% load  static %}
<aside class="sidebar static left">
									<div class="widget">
										<h4 class="widget-title">Shortcuts</h4>
										<ul class="naves">
											<li>
												<i class="ti-clipboard"></i>
												<a href="newsfeed.html" title="">News feed</a>
											</li>
											<li>
												<i class="ti-mouse-alt"></i>
												<a href="inbox.html" title="">Inbox</a>
											</li>
											<li>
												<i class="ti-files"></i>
												<a href="fav-page.html" title="">My pages</a>
											</li>
											<li>
												<i class="ti-user"></i>
												<a href="timeline-friends.html" title="">friends</a>
											</li>
											<li>
												<i class="ti-image"></i>
												<a href="timeline-photos.html" title="">images</a>
											</li>
											<li>
												<i class="ti-video-camera"></i>
												<a href="timeline-videos.html" title="">videos</a>
											</li>
											<li>
												<i class="ti-comments-smiley"></i>
												<a href="messages.html" title="">Messages</a>
											</li>
											<li>
												<i class="ti-bell"></i>
												<a href="notifications.html" title="">Notifications</a>
											</li>
											<li>
												<i class="ti-share"></i>
												<a href="people-nearby.html" title="">People Nearby</a>
											</li>
											<li>
												<i class="fa fa-bar-chart-o"></i>
												<a href="insights.html" title="">insights</a>
											</li>
											<li>
												<i class="ti-power-off"></i>
												<a href="landing.html" title="">Logout</a>
											</li>
										</ul>
									</div><!-- Shortcuts -->
									<div class="widget">
										<h4 class="widget-title">Recent Activity</h4>
										<ul class="activitiez">
											<li>
												<div class="activity-meta">
													<i>10 hours Ago</i>
													<span><a href="#" title="">Commented on Video posted </a></span>
													<h6>by <a href="time-line.html">black demon.</a></h6>
												</div>
											</li>
											<li>
												<div class="activity-meta">
													<i>30 Days Ago</i>
													<span><a href="#" title="">Posted your status. “Hello guys, how are you?”</a></span>
												</div>
											</li>
											<li>
												<div class="activity-meta">
													<i>2 Years Ago</i>
													<span><a href="#" title="">Share a video on her timeline.</a></span>
													<h6>"<a href="#">you are so funny mr.been.</a>"</h6>
												</div>
											</li>
										</ul>
									</div><!-- recent activites -->
									<div class="widget stick-widget">
										<h4 class="widget-title">Who's follownig</h4>
										<ul class="followers">
											<li>
												<figure><img src="{% static 'images/resources/friend-avatar2.jpg' %}" alt=""></figure>
												<div class="friend-meta">
													<h4><a href="time-line.html" title="">Kelly Bill</a></h4>
													<a href="#" title="" class="underline">Add Friend</a>
												</div>
											</li>
											<li>
												<figure><img src="{% static 'images/resources/friend-avatar4.jpg' %}" alt=""></figure>
												<div class="friend-meta">
													<h4><a href="time-line.html" title="">Issabel</a></h4>
													<a href="#" title="" class="underline">Add Friend</a>
												</div>
											</li>
											<li>
												<figure><img src="{% static 'images/resources/friend-avatar6.jpg' %}" alt=""></figure>
												<div class="friend-meta">
													<h4><a href="time-line.html" title="">Andrew</a></h4>
													<a href="#" title="" class="underline">Add Friend</a>
												</div>
											</li>
											<li>
												<figure><img src="{% static 'images/resources/friend-avatar8.jpg' %}" alt=""></figure>
												<div class="friend-meta">
													<h4><a href="time-line.html" title="">Sophia</a></h4>
													<a href="#" title="" class="underline">Add Friend</a>
												</div>
											</li>
											<li>
												<figure><img src="{% static 'images/resources/friend-avatar3.jpg' %}" alt=""></figure>
												<div class="friend-meta">
													<h4><a href="time-line.html" title="">Allen</a></h4>
													<a href="#" title="" class="underline">Add Friend</a>
												</div>
											</li>
										</ul>
									</div><!-- who's following -->
								</aside>

templates/base/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="" />
    <meta name="keywords" content="" />
	<title>{% block title %}{% endblock %}</title>
    <link rel="icon" href="{% static 'images/fav.png' %}" type="image/png" sizes="16x16">

    <link rel="stylesheet" href="{% static 'css/main.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/color.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">

</head>
<body>
<!--<div class="se-pre-con"></div>-->
<div class="theme-layout">

 {% include 'base/header.html' %}



	<section>
		<div class="gap2 gray-bg">
			<div class="container-fluid">
				<div class="row">
					<div class="col-lg-12">
						<div class="row merged20" id="page-contents">
							<div class="col-lg-3">
{% include 'base/aside.html'%}
							</div><!-- sidebar -->
							<div class="col-lg-6">
								<div class="central-meta">
									<div class="new-postbox">
										<figure>
											<img src="{% static 'images/resources/admin2.jpg' %}" alt="">
										</figure>

										{% include 'components/new-input.html' %}
									</div>
								</div><!-- add post new box -->
								<div class="loadMore">
								{% include 'components/user-post.html' %}
								</div>
							</div><!-- centerl meta -->
							<div class="col-lg-3">
{%  include 'base/sidebar.html' %}
							</div><!-- sidebar -->
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>

{% include 'base/footer.html' %}
</div>

	<script src="{% static 'js/main.min.js' %}"></script>
	<script src="{% static 'js/script.js' %}"></script>

</body>
</html>

templates/base/footer.html
{%  load static %}
<div class="bottombar">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<span class="copyright"><a target="_blank" href="https://www.templateshub.net">Templates Hub</a></span>
					<i><img src="{% static 'images/credit-cards.png' %}" alt=""></i>
				</div>
			</div>
		</div>
	</div>

templates/base/sidebar-chats.html
<div class="fixed-sidebar right">
		<div class="chat-friendz">
			<ul class="chat-users">
				<li>
					<div class="author-thmb">
						<img src="{% static 'images/resources/side-friend1.jpg' %}" alt="">
						<span class="status f-online"></span>
					</div>
				</li>
				<li>
					<div class="author-thmb">
						<img src="{% static 'images/resources/side-friend2.jpg' %}" alt="">
						<span class="status f-away"></span>
					</div>
				</li>
				<li>
					<div class="author-thmb">
						<img src="{% static 'images/resources/side-friend3.jpg' %}" alt="">
						<span class="status f-online"></span>
					</div>
				</li>
				<li>
					<div class="author-thmb">
						<img src="{% static 'images/resources/side-friend4.jpg' %}" alt="">
						<span class="status f-offline"></span>
					</div>
				</li>
				<li>
					<div class="author-thmb">
						<img src="{% static 'images/resources/side-friend5.jpg' %}" alt="">
						<span class="status f-online"></span>
					</div>
				</li>
				<li>
					<div class="author-thmb">
						<img src="{% static 'images/resources/side-friend6.jpg' %}" alt="">
						<span class="status f-online"></span>
					</div>
				</li>
				<li>
					<div class="author-thmb">
						<img src="{% static 'images/resources/side-friend7.jpg' %}" alt="">
						<span class="status f-offline"></span>
					</div>
				</li>
				<li>
					<div class="author-thmb">
						<img src="{% static 'images/resources/side-friend8.jpg' %}" alt="">
						<span class="status f-online"></span>
					</div>
				</li>
				<li>
					<div class="author-thmb">
						<img src="{% static 'images/resources/side-friend9.jpg' %}" alt="">
						<span class="status f-away"></span>
					</div>
				</li>
				<li>
					<div class="author-thmb">
						<img src="{% static 'images/resources/side-friend10.jpg' %}" alt="">
						<span class="status f-away"></span>
					</div>
				</li>
				<li>
					<div class="author-thmb">
						<img src="{% static 'images/resources/side-friend8.jpg' %}" alt="">
						<span class="status f-online"></span>
					</div>
				</li>
			</ul>
			<div class="chat-box">
				<div class="chat-head">
					<span class="status f-online"></span>
					<h6>Bucky Barnes</h6>
					<div class="more">
						<span class="more-optns"><i class="ti-more-alt"></i>
							<ul>
								<li>block chat</li>
								<li>unblock chat</li>
								<li>conversation</li>
							</ul>
						</span>
						<span class="close-mesage"><i class="ti-close"></i></span>
					</div>
				</div>
				<div class="chat-list">
					<ul>
						<li class="me">
							<div class="chat-thumb"><img src="{% static 'images/resources/chatlist1.jpg' %}" alt=""></div>
							<div class="notification-event">
								<span class="chat-message-item">
									Hi James! Please remember to buy the food for tomorrow! I’m gonna be handling the gifts and Jake’s gonna get the drinks
								</span>
								<span class="notification-date"><time datetime="2004-07-24T18:18" class="entry-date updated">Yesterday at 8:10pm</time></span>
							</div>
						</li>
						<li class="you">
							<div class="chat-thumb"><img src="{% static 'images/resources/chatlist2.jpg' %}" alt=""></div>
							<div class="notification-event">
								<span class="chat-message-item">
									Hi James! Please remember to buy the food for tomorrow! I’m gonna be handling the gifts and Jake’s gonna get the drinks
								</span>
								<span class="notification-date"><time datetime="2004-07-24T18:18" class="entry-date updated">Yesterday at 8:10pm</time></span>
							</div>
						</li>
						<li class="me">
							<div class="chat-thumb"><img src="{% static 'images/resources/chatlist1.jpg' %}" alt=""></div>
							<div class="notification-event">
								<span class="chat-message-item">
									Hi James! Please remember to buy the food for tomorrow! I’m gonna be handling the gifts and Jake’s gonna get the drinks
								</span>
								<span class="notification-date"><time datetime="2004-07-24T18:18" class="entry-date updated">Yesterday at 8:10pm</time></span>
							</div>
						</li>
					</ul>
					<form class="text-box">
						<textarea placeholder="Post enter to post..."></textarea>
						<div class="add-smiles">
							<span title="add icon" class="em em-expressionless"></span>
						</div>
						<div class="smiles-bunch">
							<i class="em em---1"></i>
							<i class="em em-smiley"></i>
							<i class="em em-anguished"></i>
							<i class="em em-laughing"></i>
							<i class="em em-angry"></i>
							<i class="em em-astonished"></i>
							<i class="em em-blush"></i>
							<i class="em em-disappointed"></i>
							<i class="em em-worried"></i>
							<i class="em em-kissing_heart"></i>
							<i class="em em-rage"></i>
							<i class="em em-stuck_out_tongue"></i>
						</div>
						<button type="submit"></button>
					</form>
				</div>
			</div>
		</div>
	</div><!-- right sidebar user chat -->

templates/base/sidebar.html
{% load static %}
<aside class="sidebar static right">
									<div class="widget">
										<h4 class="widget-title">Your page</h4>
										<div class="your-page">
											<figure>
												<a href="#" title=""><img src="{% static 'images/resources/friend-avatar9.jpg' %}" alt=""></a>
											</figure>
											<div class="page-meta">
												<a href="#" title="" class="underline">My page</a>
												<span><i class="ti-comment"></i><a href="insight.html" title="">Messages <em>9</em></a></span>
												<span><i class="ti-bell"></i><a href="insight.html" title="">Notifications <em>2</em></a></span>
											</div>
											<div class="page-likes">
												<ul class="nav nav-tabs likes-btn">
													<li class="nav-item"><a class="active" href="#link1" data-toggle="tab">likes</a></li>
													 <li class="nav-item"><a class="" href="#link2" data-toggle="tab">views</a></li>
												</ul>
												<!-- Tab panes -->
												<div class="tab-content">
												  <div class="tab-pane active fade show " id="link1" >
													<span><i class="ti-heart"></i>884</span>
													  <a href="#" title="weekly-likes">35 new likes this week</a>
													  <div class="users-thumb-list">
														<a href="#" title="Anderw" data-toggle="tooltip">
															<img src="{% static 'images/resources/userlist-1.jpg' %}" alt="">
														</a>
														<a href="#" title="frank" data-toggle="tooltip">
															<img src="{% static 'images/resources/userlist-2.jpg' %}" alt="">
														</a>
														<a href="#" title="Sara" data-toggle="tooltip">
															<img src="{% static 'images/resources/userlist-3.jpg' %}" alt="">
														</a>
														<a href="#" title="Amy" data-toggle="tooltip">
															<img src="{% static 'images/resources/userlist-4.jpg' %}" alt="">
														</a>
														<a href="#" title="Ema" data-toggle="tooltip">
															<img src="{% static 'images/resources/userlist-5.jpg' %}" alt="">
														</a>
														<a href="#" title="Sophie" data-toggle="tooltip">
															<img src="{% static 'images/resources/userlist-6.jpg' %}" alt="">
														</a>
														<a href="#" title="Maria" data-toggle="tooltip">
															<img src="{% static 'images/resources/userlist-7.jpg' %}" alt="">
														</a>
													  </div>
												  </div>
												  <div class="tab-pane fade" id="link2" >
													  <span><i class="ti-eye"></i>440</span>
													  <a href="#" title="weekly-likes">440 new views this week</a>
													  <div class="users-thumb-list">
														<a href="#" title="Anderw" data-toggle="tooltip">
															<img src="{% static 'images/resources/userlist-1.jpg' %}" alt="">
														</a>
														<a href="#" title="frank" data-toggle="tooltip">
															<img src="{% static 'images/resources/userlist-2.jpg' %}" alt="">
														</a>
														<a href="#" title="Sara" data-toggle="tooltip">
															<img src="{% static 'images/resources/userlist-3.jpg' %}" alt="">
														</a>
														<a href="#" title="Amy" data-toggle="tooltip">
															<img src="{% static 'images/resources/userlist-4.jpg' %}" alt="">
														</a>
														<a href="#" title="Ema" data-toggle="tooltip">
															<img src="{% static 'images/resources/userlist-5.jpg' %}" alt="">
														</a>
														<a href="#" title="Sophie" data-toggle="tooltip">
															<img src="{% static 'images/resources/userlist-6.jpg' %}" alt="">
														</a>
														<a href="#" title="Maria" data-toggle="tooltip">
															<img src="{% static 'images/resources/userlist-7.jpg' %}" alt="">
														</a>
													  </div>
												  </div>
												</div>
											</div>
										</div>
									</div><!-- page like widget -->
									<div class="widget">
										<div class="banner medium-opacity bluesh">
											<div class="bg-image" style="background-image: url(static/images/resources/baner-widgetbg.jpg)"></div>
											<div class="baner-top">
												<span><img alt="" src="{% static 'images/book-icon.png' %}"></span>
												<i class="fa fa-ellipsis-h"></i>
											</div>
											<div class="banermeta">
												<p>
													create your own favourit page.
												</p>
												<span>like them all</span>
												<a data-ripple="" title="" href="#">start now!</a>
											</div>
										</div>
									</div>
									<div class="widget stick-widget">
										<h4 class="widget-title">Profile intro</h4>
										<ul class="short-profile">
											<li>
												<span>about</span>
												<p>Hi, i am jhon kates, i am 32 years old and worked as a web developer in microsoft </p>
											</li>
											<li>
												<span>fav tv show</span>
												<p>Sacred Games, Spartcus Blood, Games of Theron </p>
											</li>
											<li>
												<span>favourit music</span>
												<p>Justin Biber, Shakira, Nati Natasah</p>
											</li>
										</ul>
									</div>
								</aside>